In [61]:
# LOad breast cancer dataset from sklearn

from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [62]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.c_[data['data'], data['target']], columns=list(data['feature_names']) + ['target'])
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0.0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0.0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0.0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0.0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0.0

In [63]:
from sklearn.model_selection import train_test_split
X = df.iloc[:,:-1]
y = df.iloc[:,-1]


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [64]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [65]:
# Logistic REgression

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [66]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred = model.predict(X_test)
accuracy_score(y_test,y_pred)

0.9736842105263158

In [67]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[41,  2],
       [ 1, 70]])

In [68]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.98      0.95      0.96        43
         1.0       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

In [69]:
# DecisionTreeClassifier

from sklearn.tree import DecisionTreeClassifier
model1 = DecisionTreeClassifier()
model1.fit(X_train,y_train)

DecisionTreeClassifier()

In [70]:
from sklearn.metrics import accuracy_score
y_pred1 = model1.predict(X_test)
accuracy_score(y_test,y_pred1)

0.9385964912280702

In [71]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred1)

array([[40,  3],
       [ 4, 67]])

In [72]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

         0.0       0.91      0.93      0.92        43
         1.0       0.96      0.94      0.95        71

    accuracy                           0.94       114
   macro avg       0.93      0.94      0.93       114
weighted avg       0.94      0.94      0.94       114

# Multiclass Precision and Recall

In [73]:
# load mnsit dataset from sklearn

from sklearn.datasets import load_digits
data = load_digits()

In [74]:
df = pd.DataFrame(data['data'],columns=data['feature_names'])
df['target'] = data['target']
df.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4

In [75]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [76]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2 , random_state = 42)

In [77]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression
LR= LogisticRegression()
LR.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [78]:
y_pred = LR.predict(X_test)

In [79]:
from sklearn.metrics import precision_score,recall_score,f1_score

print(precision_score(y_test,y_pred,average='micro'))
print(recall_score(y_test,y_pred,average='micro'))
print(f1_score(y_test,y_pred,average='micro'))

0.9694444444444444
0.9694444444444444
0.9694444444444444

In [80]:
print(precision_score(y_test,y_pred,average=None))
print(recall_score(y_test,y_pred,average=None))
print(f1_score(y_test,y_pred,average=None))

[1.         0.96551724 0.97058824 0.97058824 1.         0.91666667
 0.94444444 1.         0.96666667 0.97435897]
[1.         1.         1.         0.97058824 0.95652174 0.93617021
 0.97142857 0.97058824 0.96666667 0.95      ]
[1.         0.98245614 0.98507463 0.97058824 0.97777778 0.92631579
 0.95774648 0.98507463 0.96666667 0.96202532]

In [81]:
print(precision_score(y_test,y_pred,average='weighted'))
print(recall_score(y_test,y_pred,average='weighted'))
print(f1_score(y_test,y_pred,average='weighted'))

0.9699365066293734
0.9694444444444444
0.9695153645323796

In [82]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       0.97      1.00      0.98        28
           2       0.97      1.00      0.99        33
           3       0.97      0.97      0.97        34
           4       1.00      0.96      0.98        46
           5       0.92      0.94      0.93        47
           6       0.94      0.97      0.96        35
           7       1.00      0.97      0.99        34
           8       0.97      0.97      0.97        30
           9       0.97      0.95      0.96        40

    accuracy                           0.97       360
   macro avg       0.97      0.97      0.97       360
weighted avg       0.97      0.97      0.97       360

In [83]:
# Descition Tree

from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()
DT.fit(X_train,y_train)

DecisionTreeClassifier()

In [84]:
y_pred = DT.predict(X_test)

In [85]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.88      0.94        33
           1       0.92      0.79      0.85        28
           2       0.90      0.79      0.84        33
           3       0.74      0.91      0.82        34
           4       0.80      0.85      0.82        46
           5       0.87      0.87      0.87        47
           6       0.85      0.97      0.91        35
           7       0.86      0.88      0.87        34
           8       0.77      0.67      0.71        30
           9       0.87      0.85      0.86        40

    accuracy                           0.85       360
   macro avg       0.86      0.85      0.85       360
weighted avg       0.86      0.85      0.85       360